# Generated by Django 4.0.6 on 2022-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeks',
            name='food',
        ),
        migrations.AddField(
            model_name='weeks',
            name='food',
            field=models.ManyToManyField(default=0, to='foods.food'),
        ),
    ]
