# Generated by Django 4.0.6 on 2022-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_weeks_food_weeks_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='food',
            field=models.ManyToManyField(to='foods.food'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('Sets', 'Sets'), ('Lunch', 'Lunch'), ('BreakFast', 'BreakFast'), ('Dinner', 'Dinner')], max_length=25)),
                ('category', models.ManyToManyField(to='foods.food')),
            ],
        ),
    ]
